[FEATURE] Order, OrderLecture 구현
intensive-study/remote-class-project pull request #28
Opened 2022-02-13 05:24 UTC by yijinKim

이전 order와 orderLecture부분이 동작하지 않아 새로 구현했습니다.
현재 주문 신청 취소만 구현된 상태이면 아래와 같이 결과가 나옵니다.
리뷰 부탁드립니다.

![image](https://user-images.githubusercontent.com/33693066/153739975-ef253377-24a3-420d-95e7-7c1cadac8d90.png)

2022-02-13 07:56 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/controller/OrderController.java
> +        return new ResponseEntity<Long>(orderId, HttpStatus.OK);
상태 코드만 반환하도록 하는 게 '생성'의 목적에 부합할 것 같아요. orderId도 필요없을 것 같습니다.

2022-02-13 07:56 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/controller/OrderController.java
> +        return new ResponseEntity<Long>(orderId, HttpStatus.OK);
`@ResponseBody`가 create엔 없고 여기에 붙어 있는 이유가 있나요?
여기도 상태 코드만 반환하는 게 맞는 것 같습니다.

2022-02-13 07:56 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/controller/OrderController.java
> +//    }
이 부분 주석처리 하신 이유가 있나요?

2022-02-13 07:56 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/dto/OrderDto.java
>      private Payment payment;
Payment를 사용하게 되면 예전에 발생했던 직렬화 문제가 발생할 것 같네요.
private Long paymentId로 바꾸는 게 맞을 것 같아요.

2022-02-13 07:56 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/dto/OrderHistDto.java
> +public class OrderHistDto {
OrderHist의 경우 OrderHistory의 준말인가요? 누구나 쉽게 와닿을 수 있도록 full name을 써주시는 게 맞을 것 같아요.

2022-02-13 07:56 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/entity/Order.java
> +    }
이 부분은 영한님 강의 보시고 한 것 같습니다. 근데 영한님 강의를 보시게 되면 원리 위주로 설명하시려고 하나의 파일 안에서 작업한 경우가 있는데요. 패턴에 맞게 작업한다면 함수의 경우 서비스 단으로 빼는 게 맞다고 생각합니다.
그리고 cancelOrder가 약간 어렵네요... for문을 순회하는 것을 보면 전체 취소 함수인가요?

2022-02-13 07:56 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/service/OrderServiceImpl.java
> +    public Long orders(List<OrderDto> orderDtoList) throws IdNotExistException {
새로 강의를 주문하는 함수 같네요. createOrders나 addOrders와 같이 명확한 함수 명으로 바꿔주세요. 반환 타입도 void로 해주세요.

2022-02-13 08:04 UTC, yijinKim commented on src/main/java/org/server/remoteclass/dto/OrderDto.java
>      private Payment payment;
Payment는 현재 지불방식에 대한 enum형입니다. Payment.java로 PENDING, COMPLETE, CANCEL이 저장되어있습니다.

2022-02-13 08:04 UTC, yijinKim commented on src/main/java/org/server/remoteclass/dto/OrderHistDto.java
> +public class OrderHistDto {
네 파일명 수정하겠습니다!

2022-02-13 08:05 UTC, yijinKim commented on src/main/java/org/server/remoteclass/service/OrderServiceImpl.java
> +    public Long orders(List<OrderDto> orderDtoList) throws IdNotExistException {
네 함수명도 수정하겠습니다!

2022-02-13 09:19 UTC, yijinKim commented on src/main/java/org/server/remoteclass/controller/OrderController.java
> +//    }
이부분은 아직 구현이 완성되지 않아 주석처리 한것입니다

2022-02-13 09:19 UTC, yijinKim commented on src/main/java/org/server/remoteclass/controller/OrderController.java
> +        return new ResponseEntity<Long>(orderId, HttpStatus.OK);
네 그 방향으로 수정하겠습니다

2022-02-13 12:43 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/service/OrderServiceImpl.java
> +    public Long orders(List<OrderDto> orderDtoList) throws IdNotExistException {
생각해 봤는데, 만약에 Long 타입으로 반환된 값을 다른 함수에서 사용하게 된다면 void로 안 하셔도 될 것 같아요!

2022-02-13 14:29 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/controller/OrderController.java
>      @PutMapping("/{orderId}")
`@DeleteMapping`이 더 적합해 보이네요~
개인적으로는 주문 취소 시에 Cascade 옵션으로 엮여있는 것들도 다 삭제하면 좋을 것 같아요.

2022-02-13 14:29 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/service/OrderServiceImpl.java
> +        return orders.stream().map(order -> modelMapper.map(order, OrderHistoryDto.class)).collect(Collectors.toList());
일단 함수를 두 갈래로 분리하는 게 좋아 보여요. 하나의 함수에서 권한에 따라 관리자의 경우 전체 조회 기능을 하는 함수고, 일반 사용자의 경우 본인의 주문 내역 조회로 나뉘는 데, 이게 다른 기능을 한다고 생각합니다. 관리자도 어떤 사용자를 검색해서 주문내역을 볼 수도 있거든요. 그래서 관리자 - 전체/개별 조회, 사용자 - 본인것만 조회로 총 3개의 함수를 만드시는 게 맞다고 봐요. DTO의 경우는 볼 정보가 같기에 하나만 있으면 되겠네요.
그렇게 되면 권한을 체크하는 부분도 `@PreAuthorize` 어노테이션으로 처리할 수 있겠네요.

2022-02-13 14:31 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/controller/OrderController.java
> +        return new ResponseEntity<Long>(orderId, HttpStatus.OK);
return ResponseEntity.status(HttpStatus.OK).build();
이런 식으로 하시면 될 것 같아요.

2022-02-13 14:34 UTC, zmfl1230 requested changes

2022-02-13 14:34 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/controller/OrderController.java
> +    public ResponseEntity createOrder(@RequestBody @Valid OrderDto orderDto) throws IdNotExistException {
흠,,, 여러개의 orderLecture를 담을 수 있도록 해야하지 않을까요~!?
OrderDto 확인해보니 orderId한개만 받도록 되어 있더라구요!! 그렇게 되면 사실상 OrderLecture는 쓸모없어지게 됩니다!!
여러개의 강좌를 전달받을 수 있도록 수정해주세요~!

2022-02-13 14:34 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/OrderServiceImpl.java
> +        orderRepository.save(order);
우선 orderLectureDtoList로 반환된 값이 없는 이유가 데이터 베이스에 값이 저장되지 않았기 때문입니다.
그래서 order 생성 관련 로직을 살펴보니 Order는 save의 호출로 영속화했지만, orderLecture도 엄연한 entity임에도 영속화를 위한 호출이 발견되지 않았어요~ 
그래서 영속성을 전이시키는 옵션을 설정하셨나 살펴보니 그 부분도 따로 설정이 돼 있지 않더라구요!!  그러다보니 당연히 orderLecture는 영속화되지 못한 상태이며 해당 서비스로직의 트랜젝션이 끝나는 시점에 디비에 반영되지 못했던 것입니다!!!

이를 해결하기 위한 방법은 아래와 같습니다 :)
1. orderLecture 도 save 해주기 (그래야 영속화가 됩니다.)
2. 필드에 영속화 전이 옵션을 주기 (cascade.persist or all)

위 해결과정으로 orderLecture도 flush되는 시점에 영속상태로 만들 수 있습니다!

2022-02-13 14:34 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/OrderServiceImpl.java
> +    public Long createOrderList(List<OrderDto> orderDtoList, OrderDto orderDto) throws IdNotExistException {
이 로직은 사용하지 않는 로직인건가요~!?

2022-02-13 14:34 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/dto/OrderHistoryDto.java
> +    public OrderHistoryDto(Order order){
OrderHistoryDto의 역할은 먼가요~!?
orderLectureDtoList 는 왜 매핑을 해주지 않나요~!?

2022-02-13 14:34 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/dto/OrderHistoryDto.java
> +    public OrderHistoryDto(Order order){
추가적으로 OrderLectureDto를 보니 엔티티로(Lecture, Order) 구성되어 있더라구요!! 근데 문제는 order 안에는  OrderLecture를 컬렉션으로 가지고 있습니다. 즉, 양방향 매핑인 셈이죠. 하지만, 해당 필드는 Lazy 로딩으로 설정을 해놨기 때문에 사실상 프록시 객체가 담겨있을 겁니다. 근데 프록시 객체는 스프링에서 기본적으로 제공하는 Jackson 라이브러리에서는 json형식으로 변환될 수 없습니다. 즉, 파싱이 안되어서 에러가 나겠지요!! 
그렇다고 Lazy 로딩이 아닌 Eager로 바꾼다? 그건 좋지 못한 방법이겠지요. dto에서는 절대적으로 엔티티를 필드로 사용하지 않도록 해주세요 :) 왠만하면 orderDto로 변환해 주던지 아니면 필요한 값만 매핑해주세요!

2022-02-13 14:37 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/controller/OrderController.java
>      @PutMapping("/{orderId}")
앗,, 아마 주문 취소는 주문에 대한 상태값을 바꾸는 거라(Cancle로) PUT method가 맞을거예요!!!

2022-02-13 14:45 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/controller/OrderController.java
>      @PutMapping("/{orderId}")
그렇다면 설명을 주문 상태 변경(?) 등으로 해도 괜찮을 것 같네요.

2022-02-13 14:46 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/controller/OrderController.java
>      @PutMapping("/{orderId}")
근데 주문 상태 변경이란 말은 상태가 completed로 바뀔 수 있고, 모호하단 생각이 드네요!!
주문 취소가 개인적으로는 맞다는 생각이 들어여!! 주문 삭제 아니니!!!!

2022-02-13 14:47 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/dto/OrderHistoryDto.java
> +    public OrderHistoryDto(Order order){
저도 약간 의견 보태면, Dto의 이름을 좀 더 명확히 해주시면 좋을 것 같습니다. (예를 들면, ReqeustOrderDto, ResponseOrderListDto) 등으로 하면 역할이 더 와닿을 것 같아요.

2022-02-13 15:18 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/controller/OrderController.java
> +        return new ResponseEntity<Long>(orderId, HttpStatus.OK);
그리고 @Valid 를 사용해 주셨으면, OrderDto 내부적으로 어떤 부분을 검증할지 명시해 주는게 좋아요! 
@NotEmpty 라던지요!! 그리고 꼭 넘겨 받아야 할 필요가 있는 필드는 @NotEmpty를 명시해 주셔요!! :)

2022-02-13 15:26 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/entity/Order.java
> +    }
이건 제가 터득해 보겠습니다. 제 부분만 하다 보니 주문 관련 부분이 사실 아직 잘 이해가 안되서요 ㅠㅠ

2022-02-13 15:26 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/controller/OrderController.java
>      @PutMapping("/{orderId}")
네넵!

2022-02-14 13:49 UTC, yijinKim commented
현재 관리자 권한 if문은 모두 주석처리 되어있는 상태입니다.

2022-02-15 01:37 UTC, merged