[BUGFIX] Order주문관련 merge에서 발생한 에러 해결 + issuedCoupon으로 변경
intensive-study/remote-class-project pull request #34
Opened 2022-02-15 15:42 UTC by yijinKim

1) merge과정에서 발생한 에러 해결
2) coupon 에서 issuedCoupon으로 변경해서 적용했습니다.

2022-02-16 08:17 UTC, zmfl1230 commented
그런데 주문건에 대해 전체 강의 결제 금액 총합과 (할인이 적용되었다면 할인을 적용한 후에) 최종 금액에 대해 알 수 있어야 할 것 같아요~!

2022-02-16 08:35 UTC, zmfl1230 requested changes

2022-02-16 08:35 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/entity/Order.java
>      @OneToOne
이걸 왜 지금 봤을까요 ㅠㅠ 
Order와 Coupon의 관계에 경우 맥락상 Order가 Coupon을 nullable 한 외래키로 갖는게 맞는거 같아요~!
일반적으로 OneToOne 관계의 경우 쿠폰의 쓰임이 반드시 그 주문에 종속되는 경우가 그 예입니다. 즉, 회원과 그  회원의 장바구니 라면, 그 회원의 장바구니는 사실 그 회원에 종속되며 그 회원도 그 장바구니에 종속된 형태라고 볼 수 있어요! 
하지만, 발행된 쿠폰의 경우에는 어떤 사용자에게 발행되었다는 것은 명확하지만 그 쿠폰이 그 주문에만 쓰여야 한다(?) 이거는 좀 생각해봐야할 점인 것 같아요~ 그래서 저는 의미상 `ManyToOne`으로 매핑되는게 맞다는 생각이 들고, 의존관계 주인이 현재 이 Order  table이니 ManyToOne으로 변경하셔도 그 외 수정해야할 코드는 딱히 없을 것으로 판단됩니다!! :)

2022-02-16 08:35 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/order/OrderServiceImpl.java
>              order.setBank(requestOrderDto.getBank());
그리고 생성시 매번 Pending 상태로 주문이 생성된다면, 디비 저장 시 Default값을 `Pending`으로  설정해 주는게 더 안전해 보이네요~ :)

2022-02-16 08:35 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/order/OrderServiceImpl.java
>  //        if(coupon.isCouponValid()) { //쿠폰이 유효하면
minor한 부분이긴 하지만, 이렇게 주석처리된 채로 사용되지 않는 코드 `log.info`나 다른 코드로 대체된 코드는 지워주셨으면 좋겠어요~! 코드 가독성 측면에서요!!! 
그 외 주석이 코드의 의미를 설명하는데에 사용되는거라면 적극 찬성입니다 :)

2022-02-16 08:35 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/order/OrderServiceImpl.java
>  //        if(coupon.isCouponValid()) { //쿠폰이 유효하면
음,, 지금 발행된 쿠폰을 안넘겨 주거나, 혹은 해당 사용자에게 할당된 쿠폰이 아닌경우에는 `issuedCoupon` 이 값이 null 이 될텐데 코드상에서 null일 수 있는 상황이 존재함을 명시해주셨으면 좋겠어요~
[issuedCoupon이 `null`이 될 수 있는 상황]
- 애초에 이 주문건에 사용된 쿠폰이 없는건지 
- issuedCouponRepository.findByIssuedCouponId()호출을 통해 발행된 쿠폰을 조사했는데 조사된 쿠폰이 없는건지 

1번의 경우 굳이 쿼리를 날릴 필요가 없고, 2번의 경우 예외를 발생시켜 주셔야겠지요 :)
2번의 경우는 본인에게 할당된 쿠폰이 아님에도 사용하려고 하는 것이니!!!

2022-02-16 08:35 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/OrderServiceImpl.java
> -        return orders.stream().map(order -> new ResponseOrderDto(order)).collect(Collectors.toList());
```
orders.stream().map(order -> new ResponseOrderDto(order)).collect(Collectors.toList());
```

아래처럼 사용할 수도 있어요~!
```
orders.stream().map(ResponseOrderDto::new).collect(Collectors.toList());
```

2022-02-16 08:35 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/OrderServiceImpl.java
> -        Order order = orderRepository.findById(orderId).orElseThrow(EntityNotFoundException::new);
주문 취소의 경우, 잘못된 주문 아이디로 취소를 요청할 수도 있으니 요청한 주문 아이디로 주문이 없는 경우도 예외처리 해주시되, 클라이언트 측에 잘못된 아이디로 요청했음을 알려주셔야 할 것 같아요~! 
`orElseThrow(EntityNotFoundException::new);` 이렇게만 처리해 주시면 클라이언트측에서는 영문도 모른채 500에러를 맞보게 된답니다!

2022-02-16 08:35 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/OrderServiceImpl.java
> -//        if(user.getAuthority() == Authority.ROLE_ADMIN){
```
User user = SecurityUtil.getCurrentUserEmail()
         .flatMap(userRepository::findByEmail)
         .orElseThrow(() -> new IdNotExistException("존재하지 않는 사용자", ResultCode.ID_NOT_EXIST));
```
에서 user를 사용하지 않으시면, 아래처럼 사용해 주시고 선언해 주시고, 관리자를 위한 조회 메서드라면 관리자의 권한 체크가 필요하지 않나 싶습니다~! 현재로는 저 path로 모든 사용자가 OrderList를 받아 볼 수 있을 것 같아요!! (정말 큰일...ㅎ)

```
SecurityUtil.getCurrentUserEmail()
         .flatMap(userRepository::findByEmail)
         .orElseThrow(() -> new IdNotExistException("존재하지 않는 사용자", ResultCode.ID_NOT_EXIST));
```

2022-02-16 08:35 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/OrderServiceImpl.java
> -//        if(user.getAuthority() == Authority.ROLE_ADMIN){
그리고 개인적으로 관리자가  전체 주문, 사용자 이름으로 주문 조회는 `쿼리 스트링`으로 받아서 하나의 메서드로 묶을 수 있지 않나 싶어요~ 관리자의 주문 조회 메서드로요!

2022-02-16 10:45 UTC, yijinKim commented
> 그런데 주문건에 대해 전체 강의 결제 금액 총합과 (할인이 적용되었다면 할인을 적용한 후에) 최종 금액에 대해 알 수 있어야 할 것 같아요~!
@zmfl1230 이부분은 예전에 얘기나눌때 purchase에 포함되게 만들자고해서 erd를 설계했습니다 그런데 저도 구현하다보니 정가, 할인가 모두 order에서 구현하는게 맞을거같아요 가격부분은 order에 추가하는 걸로 수정하겠습니다

2022-02-16 10:52 UTC, yijinKim commented on src/main/java/org/server/remoteclass/entity/Order.java
>      @OneToOne
이부분도 저번에 현우님이랑 고민하던거였는데 ManyToOne으로 일단 수정해놓고 조금도 회의를 해야겠네요

2022-02-16 12:32 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/entity/Order.java
>      @OneToOne
혹시 어떤 부분이 문제셨을까요~!?

2022-02-16 12:34 UTC, zmfl1230 commented
> 그런데 주문건에 대해 전체 강의 결제 금액 총합과 (할인이 적용되었다면 할인을 적용한 후에) 최종 금액에 대해 알 수 있어야 할 것 같아요~!
> @zmfl1230 이부분은 예전에 얘기나눌때 purchase에 포함되게 만들자고해서 erd를 설계했습니다 그런데 저도 구현하다보니 정가, 할인가 모두 order에서 구현하는게 맞을거같아요 가격부분은 order에 추가하는 걸로 수정하겠습니다

흠~ purchase에선 최종 구매 금액만 관리하시죠!!!! 매번 조인하기 번거로우니 아예 한번 생성 시, 저장해 두면 좋을 것 같아여~

2022-02-16 12:37 UTC, yijinKim commented on src/main/java/org/server/remoteclass/entity/Order.java
>      @OneToOne
아니에요 문제 없습니다!

2022-02-16 13:05 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/entity/Order.java
>      @OneToOne
저는 발행된 쿠폰번호가 주문 테이블에 한 번 들어갈 수 있다고 생각해서 OneToOne이라고 가정했는데, 제가 다르게 공부했던 것 같네요.

2022-02-16 13:36 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/service/OrderServiceImpl.java
> -//        if(user.getAuthority() == Authority.ROLE_ADMIN){
이거 추후에 `@PreAuthorize` 어노테이션으로 권한 체크할 예정입니다. 일단 함수별로 테스트 하느라 안 했고, 조만간 빠르게 모든 함수에 설정하겠습니다.

2022-02-16 13:50 UTC, yijinKim commented on src/main/java/org/server/remoteclass/service/OrderServiceImpl.java
> -//        if(user.getAuthority() == Authority.ROLE_ADMIN){
관리자 권한 체크는 제가 테스트 등을 위해서 주석처리 해놓았기 때문에 주석 풀어놓겠습니다.

2022-02-16 15:03 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/service/OrderServiceImpl.java
> -//        if(user.getAuthority() == Authority.ROLE_ADMIN){
> 그리고 개인적으로 관리자가 전체 주문, 사용자 이름으로 주문 조회는 `쿼리 스트링`으로 받아서 하나의 메서드로 묶을 수 있지 않나 싶어요~ 관리자의 주문 조회 메서드로요!

유저에서의 조회 url과의 통일성이 깨질 것 같은데 괜찮을까요?

2022-02-17 03:31 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/OrderServiceImpl.java
> -//        if(user.getAuthority() == Authority.ROLE_ADMIN){
흠,,,어차피 controller를 분리하기 때문에 괜찮을 것 같습니다! :)

2022-02-18 02:31 UTC, merged