[REFACTOR] 예외처리 및 URL 수정 작업
intensive-study/remote-class-project pull request #39
Opened 2022-02-19 14:55 UTC by gusdn3477

1) 예외처리 작업을 진행하였습니다. 근데 몇 가지 예외를 정하는 게 좋을 것 같아 전체적으로 완료하진 않았습니다. 
[예외처리는 이 링크 보시고 같은 방법으로 진행하기로 해요](https://samtao.tistory.com/42)
어노테이션을 활용하여 기존 함수에 throws에 붙어있던 예외를 삭제해 약간의 가독성을 향상시켰고, 기존에 trace를 통하여 내부 정보가 반환되는 현상을 수정하여 깔끔하게 코드, 메세지 등만 반환되도록 개선하였습니다.

아래는 예외처리 과정에서 든 의문 & 질문입니다.
- 우선, IdNotExist, UsernameNotExist와 같은 에러들을 Not found(404 반환)으로 통일하는 게 더 좋지 않을까요? 또한, 기존 스프링 시큐리티 컨텍스트에서 자신의 정보를 꺼내와서 검사하는 함수에서 발생시키는 idNotExist(404) 가 아닌 Forbidden(403)이 되는 게 적합하다고 생각하는데, 자유로운 의견 있으시면 내 주세요~
- orElse(null)을 발생시키는 상황과 orElseThrow를 발생시키는 상황을 좀 규정짓는 게 중요할 것 같습니다. 이 부분만 잘 해결되면 생각보다 예외처리가 어렵지 않습니다. 
- 개인적으로 파라미터의 값이 정상 범주를 벗어나는 경우에 대한 예외처리를 추가하는 것도 필요하다고 생각합니다. 이러한 것을 규정짓고 시작하는 게 맞을 것 같아요!

2) URL 개선 작업을 진행했습니다.
- AdminController와의 분기를 통하여 /mylist 등과 같은 URL을 사용할 필요가 없어졌습니다.
- Students의 경우, 확실한 의미 전달을 위하여 /list가 필요할 것 같긴 합니다. Students 부분 봐주시고 자유로운 의견 부탁드립니다.

2022-02-20 06:49 UTC, yijinKim commented
1. IdNotExist, UsernameNotExist 저는 Not Found로 통일 동의합니다! 데이터가 있어야 하나 없는 상황이라서 통일해도 될것같습니다. 시큐리티에서 사용자가 자신의 정보 꺼내와서 검사하는 함수는 이미 로그인한 상태에서 권한이 없는 요청을 하는게 대부분일듯해서 forbidden이 적합하다고 생각합니다. 만약 로그인이 아예 안된 상황이라면 unauthorized(401)이 맞을것같고요.

2. orElse(null)은 전체 리스트 조회할 때 빈 리스트 출력과 같은 경우에 사용한다 생각합니다 orElseThrow는 하나이상의 데이터가 무조건 존재해야할때 예를 들어 본인 정보 조회, lectureId를 입력했는데 해당 데이터가 존재하지 않거나 권한이 없거나 그런 경우에 사용하면 된다고 생각합니다.

2022-02-20 06:56 UTC, yijinKim commented on src/main/java/org/server/remoteclass/controller/AdminController.java
> +    // URL 고민해 봐야 할 것 같습니다.
users, lectures 처럼 -s 붙이신 이유는 테이블명때문에 그러신건가요? 고민해봐야할것같다는 부분이 그런 부분인가요?
저는 단수명으로 썼던 이유가 'user가 1번일때 조회'와 같이 쓰려고 했던 이유도 있습니다. 하지만 쓰면서도 이부분은 조금 고민스럽긴 했어요 복수단수가 섞이면서 혼동이 올까봐요...

2022-02-20 07:00 UTC, yijinKim commented on src/main/java/org/server/remoteclass/controller/StudentController.java
> +    //수강생 전체 조회 (강의자 권한) -> 강사 권한으로 바꿔야 되겠죠..?
네 이부분은 강의자(강사) 권한으로 USER_LECTURER일때 사용가능하도록 해야합니다  hasRole('ROLE_ADMIN')은 빼야할것같네요

2022-02-20 07:03 UTC, yijinKim commented on src/main/java/org/server/remoteclass/controller/StudentController.java
> +    // 이것도 list가 없어도 될 것 같은데, list가 있어야 와닿는 면도 있어서 일단 보류하겠습니다.
이부분은 '내 강의' 'My Class'와 같이 현재 수강하고 있는 모든 강의를 볼 필요가 있을 것 같아서 추가한 기능이었습니다.

2022-02-20 09:41 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/controller/AdminController.java
> +    // URL 고민해 봐야 할 것 같습니다.
아녀 그것보다, student에서 user로 가는 게 더 큰 쪽으로 가는 것 같아서요!
그리고 예를 들면 student/1 같은 경우는 1번 학생을 조회해야 할 것 같은 느낌이 들어요 ㅠㅠ

2022-02-20 10:01 UTC, gusdn3477 commented
> 1. IdNotExist, UsernameNotExist 저는 Not Found로 통일 동의합니다! 데이터가 있어야 하나 없는 상황이라서 통일해도 될것같습니다. 시큐리티에서 사용자가 자신의 정보 꺼내와서 검사하는 함수는 이미 로그인한 상태에서 권한이 없는 요청을 하는게 대부분일듯해서 forbidden이 적합하다고 생각합니다. 만약 로그인이 아예 안된 상황이라면 unauthorized(401)이 맞을것같고요.
> 2. orElse(null)은 전체 리스트 조회할 때 빈 리스트 출력과 같은 경우에 사용한다 생각합니다 orElseThrow는 하나이상의 데이터가 무조건 존재해야할때 예를 들어 본인 정보 조회, lectureId를 입력했는데 해당 데이터가 존재하지 않거나 권한이 없거나 그런 경우에 사용하면 된다고 생각합니다.

lectureId가 없다는 건, 9번까지 id가 있는데 10번을 조회한 경우를 말씀하시나요?

2022-02-20 10:49 UTC, zmfl1230 commented
> > 1. IdNotExist, UsernameNotExist 저는 Not Found로 통일 동의합니다! 데이터가 있어야 하나 없는 상황이라서 통일해도 될것같습니다. 시큐리티에서 사용자가 자신의 정보 꺼내와서 검사하는 함수는 이미 로그인한 상태에서 권한이 없는 요청을 하는게 대부분일듯해서 forbidden이 적합하다고 생각합니다. 만약 로그인이 아예 안된 상황이라면 unauthorized(401)이 맞을것같고요.
> > 2. orElse(null)은 전체 리스트 조회할 때 빈 리스트 출력과 같은 경우에 사용한다 생각합니다 orElseThrow는 하나이상의 데이터가 무조건 존재해야할때 예를 들어 본인 정보 조회, lectureId를 입력했는데 해당 데이터가 존재하지 않거나 권한이 없거나 그런 경우에 사용하면 된다고 생각합니다.
> 
> lectureId가 없다는 건, 9번까지 id가 있는데 10번을 조회한 경우를 말씀하시나요?

네! 그런 경우 같네요~ 없는 아이디를 조회하는 경우를 말씀하시는 것 같아요! 그런경우에는 당연히 null 값을 허용해주면 안되니 예외를 던지자는 말씀이신 것 같네요!

2022-02-20 11:38 UTC, yijinKim commented on src/main/java/org/server/remoteclass/controller/AdminController.java
> +    // URL 고민해 봐야 할 것 같습니다.
현우님 말씀 무슨 의미인지 이해했습니다. 이부분은 일단은 지금 상태에서 두고 제가 추후에 query string을 적용하면 특정학생의 수강내역 조회는 "/students?userId=1" 특정 강의의 수강생 조회는 "/students?lectureId=1"이런식으로 해결되지 않을까싶습니다. 이렇게하면 의미가 좀더 분명해지면서 해결이 될까요? @gusdn3477

2022-02-20 11:40 UTC, yijinKim commented
네 제 설명이 좀 부족했는데 지영님이 말씀하신대로입니다! 지영님 보충설명 감사합니다!

2022-02-20 11:57 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/controller/AdminController.java
> +    // URL 고민해 봐야 할 것 같습니다.
아 그렇게 하면 되겠네요. 저는 좋은 방법인 것 같습니다

2022-02-20 12:25 UTC, zmfl1230 requested changes

2022-02-20 12:25 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/controller/AdminController.java
> +    // URL 고민해 봐야 할 것 같습니다.
저는 메소드의 의미와 단/복수를 지킨 아래 형식을 추천합니다! 

**수강 철회**
```
/students/{lectureId}
```

**학생의 `모든` 수강 강좌 조회**
```
/students/lectures/{userId}
```

**`특정` 강의의 모든 수강생 조회**
```
/students/lecture/{lectureId}
```

2022-02-20 12:25 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/controller/AdminController.java
> +    // URL 고민해 봐야 할 것 같습니다.
`쿼리 스트링`은 검색 시 사용합니다! 조회는 PathVariable로 넘겨주셔요!

2022-02-20 13:36 UTC, yijinKim commented on src/main/java/org/server/remoteclass/controller/LectureController.java
> +    // 수정, 삭제의 경우도 Status Code를 고려해 봐야 할 것 같습니다.
HttpStatus.CREATED와 같은 코드 말씀하시는거죠?
[링크](https://wecandev.tistory.com/38) 저도 찾아봤는데 delete의 경우 not_found를 쓰기도 하네요

2022-02-20 13:54 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/service/auth/AuthServiceImpl.java
> +            throw new IdNotExistException("Refresh Token이 유효하지 않습니다.", ErrorCode.ID_NOT_EXIST);
이것도 403 에러가 맞지 않을까요?

2022-02-20 13:54 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/service/lecture/LectureServiceImpl.java
> +                .orElseThrow(() -> new IdNotExistException("현재 로그인 상태가 아닙니다.", ErrorCode.ID_NOT_EXIST));
근데 `@PreAuthorize`를 붙여주게 되면 어노테이션을 통해 걸러지지 않나요? 
즉, "현재 로그인 상태가 아닙니다" 저 문구를 볼 상황이 없을 것 같아요. 로그인 상태면 안 뜰거고, 로그인 되지 않았으면 어노테이션으로 401이나 403이 뜰 테니까요.
차라리 저같으면 orElse(null)로 설정하고, 54번째 라인에서 추가로 user의 null 체크를 해줄 것 같아요.

2022-02-20 13:54 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/service/lecture/LectureServiceImpl.java
> +                .orElseThrow(() -> new IdNotExistException("현재 로그인 상태가 아닙니다.", ErrorCode.ID_NOT_EXIST));
SecurityUtil 관련된 부분에 다 통용되는 이야기 같아요.

2022-02-21 05:08 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/lecture/LectureServiceImpl.java
> +                .orElseThrow(() -> new IdNotExistException("현재 로그인 상태가 아닙니다.", ErrorCode.ID_NOT_EXIST));
헙 @PreAuthorize 을 통과했는데 id값이 `null`인 것도 문제가 되지 않나요? (예외를 던지는게 맞다는 의견)

2022-02-21 05:12 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/lecture/LectureServiceImpl.java
> +                .orElseThrow(() -> new IdNotExistException("현재 로그인 상태가 아닙니다.", ErrorCode.ID_NOT_EXIST));
그리고 존재하지 않는 사용자입니다. 라는 에러 메세지가 맞는 것 같아요! 
(현재 접근한 유저의 이메일을 가지고 디비에서 조회한 것이므로 만약 `not-found`면, 접근한 사용자의 이메일이 디비에 없다는 의미입니다!)

2022-02-21 05:45 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/service/lecture/LectureServiceImpl.java
> +                .orElseThrow(() -> new IdNotExistException("현재 로그인 상태가 아닙니다.", ErrorCode.ID_NOT_EXIST));
토큰에 있는 User 객체의 ID가 null인 상황을 말씀하시는 거겠죠..?

일단 생각을 정리해 보면.
인증이 성공한 경우 스프링 시큐리티 컨텍스트에 저장도 하고, 토큰을 발급해 주는 것으로 알고 있습니다.
jwt에서 토큰 시간도 유효하고, 안에 있는 권한도 잘 체크가 된 상태에서(`@PreAuthorize` 통과)
스프링 시큐리티 컨텍스트에 저장된 유저 정보가 없는 상황이 있을까?에 대해서 생각해 본 결과..
누군가가 jwt를 엇비슷하게 위조하였지만 jwt 안에 있는 User 객체 안의 ID(저희같은 경우는 이메일이 들어가 있을 겁니다)가 null인 경우가 있을 것 같은데(맞나요?)
그 외의 상황은 딱히 떠오르지 않습니다. 로그인 시에 db에 있는 값과 로그인 시에 입력한 email을 확인해서 토큰이 발급되서요!

2022-02-21 05:45 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/lecture/LectureServiceImpl.java
> +                .orElseThrow(() -> new IdNotExistException("현재 로그인 상태가 아닙니다.", ErrorCode.ID_NOT_EXIST));
그리고 왠지 Role을 검증하는 과정에서 security에서 현재 접근하는 사용자 존재 여부도 체크할 거 같긴해서 PreAuthorize가 붙은 컨트롤러에서 호출하는 서비스 모두 아래처럼 사용해도 무방할 거 같기는 해요
```
User user = SecurityUtil.getCurrentUserEmail().flatMap(userRepository::findByEmail)
```

2022-02-21 05:57 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/student/StudentServiceImpl.java
>          List<Student> students = null;
글고 왠만하면 `null`로 초기화 해주시는 것보다  사용하실 List 구현체로 초기화해주시고, Role의 경우 ROLE_STUDENT로 서비스 단에  ROLE을 걸어주셔요 @PreAuthorize로요~  그러면 아래처럼 좀 더 깔끔하게 구현 가능합니다!

```
List<Student> students = studentRepository.findByUser_UserIdOrderByLecture_StartDateDesc(user.getUserId());
return students.stream().map(lecture-> ResponseLectureFromStudentDto.from(lecture)).collect(Collectors.toList());
   
```

2022-02-21 05:58 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/service/lecture/LectureServiceImpl.java
> +                .orElseThrow(() -> new IdNotExistException("현재 로그인 상태가 아닙니다.", ErrorCode.ID_NOT_EXIST));
```
private UserDetails createUserDetails(User user){
        GrantedAuthority grantedAuthority = new SimpleGrantedAuthority(user.getAuthority().toString());
        return new org.springframework.security.core.userdetails.User(
                String.valueOf(user.getEmail()),
                        user.getPassword(),
                        Collections.singleton(grantedAuthority)
        );
    }
```

User 객체에(User Entity가 아닌 스프링 시큐리티에서 사용되는 User 객체입니다) 이메일, 비밀번호, 권한을 담아서 만들어 줍니다. 이걸 바탕으로 권한 체크 시에 사용하는 것 같아요!

2022-02-21 05:59 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/service/lecture/LectureServiceImpl.java
> +                .orElseThrow(() -> new IdNotExistException("현재 로그인 상태가 아닙니다.", ErrorCode.ID_NOT_EXIST));
토큰을 가지고 인증받는 방식에서 정확한 순서와 호출되는 함수를 잘 모르겠습니다. 내일 회의 시간때까지 공부해서 알려드리겠습니다.
스프링 시큐리티 내부에서 실행되는 함수도 많아서 좀 어렵긴 해요..

2022-02-21 06:01 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/service/student/StudentServiceImpl.java
>          List<Student> students = null;
`@PreAuthorize`의 경우 스프링 시큐리티에서 기본적으로 설정해 놓은 3개의 권한을 체크할 수 있는 것으로 알고 있어요(게스트, 유저 관리자)
Student, Lecturerer 의 경우 저희가 임의적으로 가능한 지는 해봐야 알 것 같습니다~!

2022-02-21 06:08 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/lecture/LectureServiceImpl.java
> +                .orElseThrow(() -> new IdNotExistException("현재 로그인 상태가 아닙니다.", ErrorCode.ID_NOT_EXIST));
우선 스프링 시큐리티가 발급해준 토큰의 경우 id(저희의 경우, email) 로 조사한 사용자의 정보가 null인데 토큰을 발급해 주진 않을 것입니다! 그래서 만약 토큰이 유효하다면, 이미 인증된 사용자임을 나타내는 것이겠죠!

2022-02-21 06:12 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/lecture/LectureServiceImpl.java
> +                .orElseThrow(() -> new IdNotExistException("현재 로그인 상태가 아닙니다.", ErrorCode.ID_NOT_EXIST));
넵!!

2022-02-21 06:20 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/student/StudentServiceImpl.java
>          List<Student> students = null;
[PreAuthorize Custom!](https://dreamix.eu/blog/java/implementing-custom-authorization-function-for-springs-pre-and-post-annotations)

2022-02-21 06:26 UTC, yijinKim commented on src/main/java/org/server/remoteclass/service/auth/AuthServiceImpl.java
> +            throw new IdNotExistException("Refresh Token이 유효하지 않습니다.", ErrorCode.ID_NOT_EXIST);
넵 401 unauthorized가 맞을것같네요

2022-02-21 06:53 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/student/StudentServiceImpl.java
>          List<Student> students = null;
위 저부분 제가 커밋할게요~!

2022-02-21 06:55 UTC, yijinKim commented on src/main/java/org/server/remoteclass/service/lecture/LectureServiceImpl.java
> +                .orElseThrow(() -> new IdNotExistException("현재 로그인 상태가 아닙니다.", ErrorCode.ID_NOT_EXIST));
AdminController의 경우 Preauthorize가 붙어있으니까 관리자 권한 체크하는 if문-throw예외문은 모두 없애주는게 맞을까요?

2022-02-21 06:58 UTC, zmfl1230 commented
`@PreAuthorize` 로 강의자, 학생 권한 체크 가능하도록 구현했고, 
강의자 혹은 학생으로의 접근만 허용하고 싶으실 경우엔

`AccessVerification` DI 하시고, 아래처럼 사용해 주시면 됩니다!
당연 DI는 사용 클래스 생성자로 넘겨주셔야 겠죠~?

```
@PreAuthorize("@accessVerification.hasAccessOnlyLecturer()")
```

```
@PreAuthorize("@accessVerification.hasAccessOnlyStudent()")
```

2022-02-21 07:02 UTC, zmfl1230 commented
근데 현우님 지금 SecurityUtil 보면서 생각이 든건데 static 선언해 주셨는데 빈으로 등록해 주신 이유가 있을까요~?

2022-02-21 07:10 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/lecture/LectureServiceImpl.java
> +                .orElseThrow(() -> new IdNotExistException("현재 로그인 상태가 아닙니다.", ErrorCode.ID_NOT_EXIST));
넵 :)

2022-02-21 08:35 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/service/student/StudentServiceImpl.java
>          List<Student> students = null;
와우..

2022-02-21 08:36 UTC, gusdn3477 commented
> 근데 현우님 지금 SecurityUtil 보면서 생각이 든건데 static 선언해 주셨는데 빈으로 등록해 주신 이유가 있을까요~?

static을 빼고 bean으로 등록하는 게 맞는거죠?

2022-02-21 10:13 UTC, gusdn3477 commented
> 근데 현우님 지금 SecurityUtil 보면서 생각이 든건데 static 선언해 주셨는데 빈으로 등록해 주신 이유가 있을까요~?

이거 한번만 설명해 주세요 ㅠㅠㅠ

2022-02-21 10:37 UTC, zmfl1230 commented
> > 근데 현우님 지금 SecurityUtil 보면서 생각이 든건데 static 선언해 주셨는데 빈으로 등록해 주신 이유가 있을까요~?
> 
> static을 빼고 bean으로 등록하는 게 맞는거죠?

엇 ~ 다름이 아니라 @Component가 딱히 필요 없을 것 같아 여쭤본 부분입니다!

해당 Util을 빈으로 등록해 DI 해주셔도 되지만, 아래와 같은 이유로 @Component를 제거하는 것이 더 합리적이라고 판단됩니다!

- **어떤 빈 오브젝트와도 의존관계를 맺고 있지 않다는 점**
- 전역적으로 사용될 필요가 있는 점
- 이미 해당 Static으로 선언돼 전역적으로 사용되고 있다는 점(빈으로 등록하게 되면 사용한 모든 레이어에 주입해주어야 함 -> 수정이 번거로움)

🥲댓글을 달았는데 사라져서 기억을 더듬으며, 다시 쓰는 중...

2022-02-21 10:47 UTC, gusdn3477 commented
> > > 근데 현우님 지금 SecurityUtil 보면서 생각이 든건데 static 선언해 주셨는데 빈으로 등록해 주신 이유가 있을까요~?
> > 
> > 
> > static을 빼고 bean으로 등록하는 게 맞는거죠?
> 
> 엇 ~ 다름이 아니라 @component가 딱히 필요 없을 것 같아 여쭤본 부분입니다!
> 
> 해당 Util을 빈으로 등록해 DI 해주셔도 되지만, 아래와 같은 이유로 @component를 제거하는 것이 더 합리적이라고 판단됩니다!
> 
> * **어떤 빈 오브젝트와도 의존관계를 맺고 있지 않다는 점**
> * 전역적으로 사용될 필요가 있는 점
> * 이미 해당 Static으로 선언돼 전역적으로 사용되고 있다는 점(빈으로 등록하게 되면 사용한 모든 레이어에 주입해주어야 함 -> 수정이 번거로움)
> 
> 🥲댓글을 달았는데 사라져서 기억을 더듬으며, 다시 쓰는 중...

아 죄송해요. 수정 후에 검사(?) 맡으려 했는데 댓글을 다셨네요
아까 댓글은 static을 제거하고 의존성 주입을 하는 게 맞는지에 대해 질문을 드렸습니다.

2022-02-21 10:53 UTC, zmfl1230 commented
> > > > 근데 현우님 지금 SecurityUtil 보면서 생각이 든건데 static 선언해 주셨는데 빈으로 등록해 주신 이유가 있을까요~?
> > > 
> > > 
> > > static을 빼고 bean으로 등록하는 게 맞는거죠?
> > 
> > 
> > 엇 ~ 다름이 아니라 @component가 딱히 필요 없을 것 같아 여쭤본 부분입니다!
> > 해당 Util을 빈으로 등록해 DI 해주셔도 되지만, 아래와 같은 이유로 @component를 제거하는 것이 더 합리적이라고 판단됩니다!
> > 
> > * **어떤 빈 오브젝트와도 의존관계를 맺고 있지 않다는 점**
> > * 전역적으로 사용될 필요가 있는 점
> > * 이미 해당 Static으로 선언돼 전역적으로 사용되고 있다는 점(빈으로 등록하게 되면 사용한 모든 레이어에 주입해주어야 함 -> 수정이 번거로움)
> > 
> > 🥲댓글을 달았는데 사라져서 기억을 더듬으며, 다시 쓰는 중...
> 
> 아 죄송해요. 수정 후에 검사(?) 맡으려 했는데 댓글을 다셨네요 아까 댓글은 static을 제거하고 의존성 주입을 하는 게 맞는지에 대해 질문을 드렸습니다.

앗 넵 질문에 대한 답변이 되셨을까요~?!

2022-02-21 10:55 UTC, gusdn3477 commented
> > > > > 근데 현우님 지금 SecurityUtil 보면서 생각이 든건데 static 선언해 주셨는데 빈으로 등록해 주신 이유가 있을까요~?
> > > > 
> > > > 
> > > > static을 빼고 bean으로 등록하는 게 맞는거죠?
> > > 
> > > 
> > > 엇 ~ 다름이 아니라 @component가 딱히 필요 없을 것 같아 여쭤본 부분입니다!
> > > 해당 Util을 빈으로 등록해 DI 해주셔도 되지만, 아래와 같은 이유로 @component를 제거하는 것이 더 합리적이라고 판단됩니다!
> > > 
> > > * **어떤 빈 오브젝트와도 의존관계를 맺고 있지 않다는 점**
> > > * 전역적으로 사용될 필요가 있는 점
> > > * 이미 해당 Static으로 선언돼 전역적으로 사용되고 있다는 점(빈으로 등록하게 되면 사용한 모든 레이어에 주입해주어야 함 -> 수정이 번거로움)
> > > 
> > > 🥲댓글을 달았는데 사라져서 기억을 더듬으며, 다시 쓰는 중...
> > 
> > 
> > 아 죄송해요. 수정 후에 검사(?) 맡으려 했는데 댓글을 다셨네요 아까 댓글은 static을 제거하고 의존성 주입을 하는 게 맞는지에 대해 질문을 드렸습니다.
> 
> 앗 넵 질문에 대한 답변이 되셨을까요~?!

네넵 되었습니다~~!!

2022-02-21 12:32 UTC, gusdn3477 commented
시간 될 때마다 Dto에 제약 조건 걸어두면 좋을 것 같아요!
회원가입 시 name의 길이, 이벤트 생성 시에 title의 길이 등이요~!

2022-02-21 12:46 UTC, yijinKim commented
> 시간 될 때마다 Dto에 제약 조건 걸어두면 좋을 것 같아요! 회원가입 시 name의 길이, 이벤트 생성 시에 title의 길이 등이요~!

제가 알기로는 Long, Integer 타입의 경우 NotEmpty보다 NotNull로 사용해도 되지 않나요?

2022-02-21 12:56 UTC, gusdn3477 commented
> > 시간 될 때마다 Dto에 제약 조건 걸어두면 좋을 것 같아요! 회원가입 시 name의 길이, 이벤트 생성 시에 title의 길이 등이요~!
> 
> 제가 알기로는 Long, Integer 타입의 경우 NotEmpty보다 NotNull로 사용해도 되지 않나요?

그래도 될 것 같아요. 근데 `@NotNull`를 적용하려면 long, integer 같은 원시 타입을 사용하면 안 되겠죠?

2022-02-22 14:52 UTC, gusdn3477 commented
저희 Security Util 사용 부분 다 지워도 되는거죠?

2022-02-22 15:17 UTC, yijinKim commented
user를 사용하지 않는 부분은 지워도 되지만 사용하는 부분은 
`User user = SecurityUtil.getCurrentUserEmail().flatMap(userRepository::findByEmail)`
이렇게 하는게 좋지 않냐고 오전에 했던거같아요

2022-02-22 15:27 UTC, yijinKim commented
@gusdn3477  현우님 Coupon의 couponUsed는 사용안한 쿠폰은 default값 0이고 IssuedCoupon의 couponValid는 유효한 값이 default 1인건가요?

2022-02-22 15:52 UTC, yijinKim commented on src/main/java/org/server/remoteclass/dto/user/RequestUserDto.java
> +    @Range(min = 8, max = 30)
@Range는 숫자의 범위, @Length(min=,max=)가 문자열의 길이로 알고있습니다

2022-02-22 15:54 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/dto/user/RequestUserDto.java
> +    @Range(min = 8, max = 30)
아 그렇군요. 저는 가입이 안 되길래 (에러 문구 : org.server.remoteclass.dto.user.RequestUserDto@44190e65: 8에서 30 사이여야 합니다") 잘 작동하는 줄 알았네요. 수정하겠습니다.

2022-02-22 15:55 UTC, gusdn3477 commented
> @gusdn3477 현우님 Coupon의 couponUsed는 사용안한 쿠폰은 default값 0이고 IssuedCoupon의 couponValid는 유효한 값이 default 1인건가요?

일단 Coupon에 couponValid가 있고, IssuedCoupon에 couponUsed가 있습니다. 이것도 그냥 Valid로 통일을 할까요? 괜히 헷갈릴 수 있을 것 같네요.

2022-02-22 15:58 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/dto/user/RequestUserDto.java
> +    @Range(min = 8, max = 30)
@Size로 적어둔 것도 있네요. (@Size는 길이를 체크합니다!) @Size로 통일하겠습니다.

2022-02-22 16:04 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/dto/user/RequestUserDto.java
> +    @Range(min = 8, max = 30)
저는 쿠폰 부분의 예외만 잘 처리하면 일단 마무리 된 듯 해요. CouponRepository를 제네릭을 활용해서 구현했는데 조금 공부가 필요할 듯 합니다!

2022-02-22 16:17 UTC, yijinKim commented
> > @gusdn3477 현우님 Coupon의 couponUsed는 사용안한 쿠폰은 default값 0이고 IssuedCoupon의 couponValid는 유효한 값이 default 1인건가요?
> 
> 일단 Coupon에 couponValid가 있고, IssuedCoupon에 couponUsed가 있습니다. 이것도 그냥 Valid로 통일을 할까요? 괜히 헷갈릴 수 있을 것 같네요.

제가 order에서 issuedCoupon으로 가격할인 적용하고 나서 orderServiceImpl에서 issuedCoupon을 사용함으로 바꿔야할것같아요 issuedCoupon만 used로 바꾸면 될거같아서요 set(1)로 설정하는게 맞을까요?

2022-02-23 01:52 UTC, gusdn3477 commented
> > > @gusdn3477 현우님 Coupon의 couponUsed는 사용안한 쿠폰은 default값 0이고 IssuedCoupon의 couponValid는 유효한 값이 default 1인건가요?
> > 
> > 
> > 일단 Coupon에 couponValid가 있고, IssuedCoupon에 couponUsed가 있습니다. 이것도 그냥 Valid로 통일을 할까요? 괜히 헷갈릴 수 있을 것 같네요.
> 
> 제가 order에서 issuedCoupon으로 가격할인 적용하고 나서 orderServiceImpl에서 issuedCoupon을 사용함으로 바꿔야할것같아요 issuedCoupon만 used로 바꾸면 될거같아서요 `setCouponUsed(true)`로 설정하는게 맞을까요?

네네. 근데 지금 생각해보니 헷갈릴 것 같긴 하네요. 이것도 협의 후에 통일시켜봐요.

2022-02-23 05:41 UTC, zmfl1230 commented
> > > > @gusdn3477 현우님 Coupon의 couponUsed는 사용안한 쿠폰은 default값 0이고 IssuedCoupon의 couponValid는 유효한 값이 default 1인건가요?
> > > 
> > > 
> > > 일단 Coupon에 couponValid가 있고, IssuedCoupon에 couponUsed가 있습니다. 이것도 그냥 Valid로 통일을 할까요? 괜히 헷갈릴 수 있을 것 같네요.
> > 
> > 
> > 제가 order에서 issuedCoupon으로 가격할인 적용하고 나서 orderServiceImpl에서 issuedCoupon을 사용함으로 바꿔야할것같아요 issuedCoupon만 used로 바꾸면 될거같아서요 `setCouponUsed(true)`로 설정하는게 맞을까요?
> 
> 네네. 근데 지금 생각해보니 헷갈릴 것 같긴 하네요. 이것도 협의 후에 통일시켜봐요.

흠,,, 저는 의미상 사용했음을 알리는 used가 좋을 것 같기는 해요!!

2022-02-23 05:45 UTC, zmfl1230 commented
> user를 사용하지 않는 부분은 지워도 되지만 사용하는 부분은
> `User user = SecurityUtil.getCurrentUserEmail().flatMap(userRepository::findByEmail)`
> 이렇게 하는게 좋지 않냐고 오전에 했던거같아요

넵 이렇게 되면 익명의 사용자 접근을 허용한 controller를 제외한 나머지는 모두 사용자 검증이 되어있어야 합니다! (PreAuthorize로!)

2022-02-23 07:02 UTC, gusdn3477 commented
@yijinKim 님이 사용하시는 파트니까 이진님이 결정하시는 것 추천드립니다. 지금 구현된 코드로도 작동시킬 수 있을 것 같아요!
만약 Coupon과 IssueCoupon을 통일하게 된다면 지영님 말씀대로 CouponUsed (default 0)으로 맞추는 게 좋아 보입니다!
제가 짠 코드라 저는 헷갈리지 않지만, 헷갈릴 여지(?)를 방지하는 것도 중요하다고 생각해요~~

2022-02-23 07:02 UTC, gusdn3477 commented
> @yijinKim 님이 사용하시는 파트니까 이진님이 결정하시는 것 추천드립니다. 지금 구현된 코드로도 작동시킬 수 있을 것 같아요! 만약 Coupon과 IssueCoupon을 통일하게 된다면 지영님 말씀대로 CouponUsed (default 0)으로 맞추는 게 좋아 보입니다! 제가 짠 코드라 저는 헷갈리지 않지만, 헷갈릴 여지(?)를 방지하는 것도 중요하다고 생각해요~~

true, false로 설정해 주시면 되고, mysql에 들어갈 때는 tinyInt형으로 매칭되어 1, 0 값으로 들어갑니다.

2022-02-23 09:25 UTC, yijinKim commented
> > user를 사용하지 않는 부분은 지워도 되지만 사용하는 부분은
> > `User user = SecurityUtil.getCurrentUserEmail().flatMap(userRepository::findByEmail)`
> > 이렇게 하는게 좋지 않냐고 오전에 했던거같아요
> 
> 넵 이렇게 되면 익명의 사용자 접근을 허용한 controller를 제외한 나머지는 모두 사용자 검증이 되어있어야 합니다! (PreAuthorize로!)
-> 넵 controller에 PreAuthorize모두 달려있습니다

2022-02-23 09:45 UTC, yijinKim commented
현우님이 Coupon의 couponValid 의미를 써놓으신걸 보니 "쿠폰 발행이 가능함" 이라서 사용함?이랑은  좀 다르지않나...싶습니다

2022-02-23 09:46 UTC, yijinKim commented
@zmfl1230  @gusdn3477  수정할게 어느정도 정리된거 같으면 한번 develop 브랜치에 머지해보는건 어떨가 싶습니다!

2022-02-23 09:58 UTC, merged