[FEATURE] 구매확정 시 수강생 추가 기능
intensive-study/remote-class-project pull request #46
Opened 2022-02-25 01:00 UTC by yijinKim

기존의 student의 수강신청이 큰 의미가 없지않을까 생각해서 구매를 확정하면 student테이블에 수강생이 삽입되도록 연결해봤습니다. 수강 취소를 하면 그 강의가 시작전일 경우 구매금액이 (-가격)이 되어 환불(?)처럼 되도록 구현했습니다.
이 기능은 추가하는게 좋을지 아닐지 얘기해봤으면 합니다...

2022-02-26 08:28 UTC, gusdn3477 requested changes

2022-02-26 08:28 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/controller/AdminController.java
> +    public ResponseEntity<List<ResponsePurchaseDto>> getOnePurchaseByUserIdByAdmin(@PathVariable("userId") Long userId) {
URI에 전달되는 파라미터가 없는 것 같은데요?

2022-02-26 08:28 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/controller/PurchaseController.java
> +    @ApiOperation(value = "구매 내역 전체 조회", notes = "사용자의 생성된 전체 구매 내역 조회함.")
더 나은 URI가 있는지 고민해 봐야 할 것 같아요. 주문/구매의 경계를 좀 명확히 하는 게 좋아 보입니다. 저는 주문 부분 취소를 /purchase/lecture/{lectureId}로 하면 어떨까 싶네요.

2022-02-26 08:28 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/controller/PurchaseController.java
>      }
사소하긴 한건데 복수형으로 맞춰주시면 좋을 것 같습니다. (Purchase -> Purchases)

2022-02-26 08:28 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/dto/purchase/ResponsePurchaseDto.java
> +    private Long orderName;
이게 혹시 '주문자 이름' 인가요? 처음 본 경우에 어떤 의미인지 정확히 와닿지 않아요~!

2022-02-26 08:28 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/jpa/StudentRepository.java
> +    Student findStudentByLecture_LectureId(Long lectureId);
이 부분 혹시 오류 뜨지 않나요? JPQL에서 파라미터 이용하는 경우 `@Param` 붙여줘야 잘 작동하는 걸로 알고 있어서요.

2022-02-26 08:28 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/service/purchase/PurchaseService.java
> +    void cancelAll(Long purchaseId);
이것도 뒤에 Purchase를 붙이는 식으로 해서 좀 더 와닿는 단어로 변경하면 좋을 것 같아요.

2022-02-26 08:28 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/service/purchase/PurchaseServiceImpl.java
> +            studentRepository.deleteByUser_UserIdAndOrder_OrderId(user.getUserId(), order.getOrderId());
purchase가 null이거나 isValidPurchase가 false인 경우에는 아무 로직이 작동되지 않고 상태코드 200이 반환될 것 같은데, 이 부분에 대해 보완이 필요할 것 같아요.

2022-02-27 00:33 UTC, yijinKim commented on src/main/java/org/server/remoteclass/controller/AdminController.java
> +    public ResponseEntity<List<ResponsePurchaseDto>> getOnePurchaseByUserIdByAdmin(@PathVariable("userId") Long userId) {
어!!! 지적해주셔서 감사합니다! 빠졌나보네요...

2022-02-27 00:35 UTC, yijinKim commented on src/main/java/org/server/remoteclass/controller/PurchaseController.java
> +    @ApiOperation(value = "구매 내역 전체 조회", notes = "사용자의 생성된 전체 구매 내역 조회함.")
주문의 강의 부분취소라서 그 url이 더 직관적일 수도 있겠네요

2022-02-27 00:35 UTC, yijinKim commented on src/main/java/org/server/remoteclass/controller/PurchaseController.java
>      }
넵! 수정하겠습니다!

2022-02-27 00:55 UTC, yijinKim commented on src/main/java/org/server/remoteclass/dto/purchase/ResponsePurchaseDto.java
> +    private Long orderName;
구매자(주문자)의 아이디를 의미합니다. userId가 더 와닿을까요?

2022-02-27 01:03 UTC, yijinKim commented on src/main/java/org/server/remoteclass/service/purchase/PurchaseService.java
> +    void cancelAll(Long purchaseId);
넵!

2022-02-27 01:07 UTC, yijinKim commented on src/main/java/org/server/remoteclass/service/purchase/PurchaseServiceImpl.java
> +            studentRepository.deleteByUser_UserIdAndOrder_OrderId(user.getUserId(), order.getOrderId());
네! 예외 처리 해두겠습니다!

2022-02-27 04:09 UTC, yijinKim commented on src/main/java/org/server/remoteclass/jpa/StudentRepository.java
> +    Student findStudentByLecture_LectureId(Long lectureId);
저는 잘 작동했습니다...

2022-02-27 06:23 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/dto/purchase/ResponsePurchaseDto.java
> +    private Long orderName;
저는 userId가 더 낫다고 생각합니다. 일단 아이디와 Name이 정확히 매칭되지 않는 것 같아요.

2022-02-27 10:41 UTC, yijinKim commented
장바구니의 모든 강의를 주문으로 넘기는 기능도 구현했습니다. 한번 더 리뷰 부탁드립니다! @gusdn3477 @zmfl1230

2022-02-28 06:23 UTC, gusdn3477 commented
혹시 정액할인 쿠폰 적용 시에 쿠폰 할인 금액이 강의 가격을 넘는 경우에 대해 처리가 되었을까요?

2022-02-28 06:39 UTC, yijinKim commented
> 혹시 정액할인 쿠폰 적용 시에 쿠폰 할인 금액이 강의 가격을 넘는 경우에 대해 처리가 되었을까요?

이부분은 제가 고려하지 않았네요 해당 내용 추가해놓겠습니다!

2022-02-28 07:58 UTC, gusdn3477 commented
> > 혹시 정액할인 쿠폰 적용 시에 쿠폰 할인 금액이 강의 가격을 넘는 경우에 대해 처리가 되었을까요?
> 
> 이부분은 제가 고려하지 않았네요 해당 내용 추가해놓겠습니다!
> 
> +) fixDiscountCoupon이 정가보다 작은 경우에만 쿠폰이 적용되고 그 외에는 BadRequest 에러 처리했습니다. @gusdn3477

사용자 입장에서 베스트는 차액의 경우 포인트 등으로 환산되는 방법인 것 같아요.

2022-02-28 12:47 UTC, yijinKim commented
> > > 혹시 정액할인 쿠폰 적용 시에 쿠폰 할인 금액이 강의 가격을 넘는 경우에 대해 처리가 되었을까요?
> > 
> > 
> > 이부분은 제가 고려하지 않았네요 해당 내용 추가해놓겠습니다!
> > +) fixDiscountCoupon이 정가보다 작은 경우에만 쿠폰이 적용되고 그 외에는 BadRequest 에러 처리했습니다. @gusdn3477
> 
> 사용자 입장에서 베스트는 차액의 경우 포인트 등으로 환산되는 방법인 것 같아요.

어떤 차액을 말씀하시는건지 잘 모르겠어요

2022-02-28 13:18 UTC, gusdn3477 commented
> > > > 혹시 정액할인 쿠폰 적용 시에 쿠폰 할인 금액이 강의 가격을 넘는 경우에 대해 처리가 되었을까요?
> > > 
> > > 
> > > 이부분은 제가 고려하지 않았네요 해당 내용 추가해놓겠습니다!
> > > +) fixDiscountCoupon이 정가보다 작은 경우에만 쿠폰이 적용되고 그 외에는 BadRequest 에러 처리했습니다. @gusdn3477
> > 
> > 
> > 사용자 입장에서 베스트는 차액의 경우 포인트 등으로 환산되는 방법인 것 같아요.
> 
> 어떤 차액을 말씀하시는건지 잘 모르겠어요

지금은 시간상 구현이 불가능할것 같아요! 만약 5000원 짜리 쿠폰에 3000원 짜리 강의라면 2000원이 포인트로 적립되는 식으로 추후에 기회가 주어진다면 만들어보면 좋을 것 같아요~

2022-03-01 09:32 UTC, yijinKim commented
두 가지 모두 @RequestParam으로 구현해놨습니다. 
1. 부분 취소 또는 전체 취소
[url]    ~/purchases/lecture?lectureId=1&lectureId=2&purchaseId=1
이미 구매완료한 purchaseId에서 수강 취소하고 싶은 강의 아이디를 선택하여 넘기도록 구현했습니다. 강의 아이디를 입력안할경우 해당 구매아이디의 강의들이 전체 취소가 되도록 구현했습니다.

3. 장바구니 부분 주문 또는 전체 주문
[url]    ~/orders/carts?lectureId=1&lectureId=2
장바구니에 있는 강의 아이디를 선택해서 주문할 수 있고 주문하지 않은 강의들은 그대로 장바구니에 남아있습니다.
강의아이디 선택하지 않을 경우(~/orders/carts)에는 장바구니의 전체가 주문되도록 했습니다.
@gusdn3477  @zmfl1230  리뷰 부탁드립니다~

2022-03-01 11:54 UTC, zmfl1230 requested changes

2022-03-01 11:54 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/controller/PurchaseController.java
> +    public ResponseEntity cancelPurchase(@RequestParam("purchaseId") Long purchaseId, @RequestParam(value = "lectureId", required = false, defaultValue = "") List<Long> lectureIdList) {
으음..? 왜 `lectureIdList`를 RequestParam으로 넘겨주시죠?!!
Body로 받으시죠!! RequestParam은 쿼리 스트링 쓰실때 사용하셔요!
추가적으로 부분 취소를 한다는 의미는 어떤 강좌는 반드시 취소가 된다는 의미니 required = false도 제거할 필요가 있어보여요!!
그렇지만 Body로 바꿔주셔요! 만약 부분 취소하는 강좌가 10개 이상이 될 경우, URI가 엄청 길어집니다!

2022-03-01 11:54 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/order/OrderServiceImpl.java
> +        order.setOrderStatus(OrderStatus.PENDING);
order_status column에 기본값 `PENDING` 으로 해주셨으니 이부분 지워주셔요~!

2022-03-01 11:54 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/order/OrderServiceImpl.java
> +            if (issuedCoupon == null) {  //없는 쿠폰 입력했을 때
왠만하면  null체크는 optional<T> 로 가져와 orElseThrow(() -> {}) 으로 처리해주시는게 좋습니다.!

2022-03-01 11:54 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/order/OrderServiceImpl.java
> +    public void createOrderFromCart(RequestOrderFromCartDto requestOrderFromCartDto, List<Long> requestLectureIdList) {
그리고 클라이언트에서 장바구니에 모든 상품 구매인 경우에도, requestLectureIdList 에 모든 강좌의 정보를 담아서 보내줄 거예요!
그러면 중복되는 검증들을 제거하고 아래처럼 수정해 볼 수 있을 것 같아요~ 물론 필요한 부분(`findByLecture_LectureIdAndUser_UserId`)은 Optional로 가져온 상황입니다!
또 cartRepository.findByLecture_LectureIdAndUser_UserId 로 해당 유저의 선택한 강의에 대한 존재여부를 확인하기 때문에 장바구니가 비었나와 같은 불필요한 쿼리를 삭제했어요! 
```
@Override
    @Transactional
    public void createOrderFromCart(RequestOrderFromCartDto requestOrderFromCartDto, List<Long> requestLectureIdList) {
        User user = SecurityUtil.getCurrentUserEmail()
                .flatMap(userRepository::findByEmail)
                .orElseThrow(() -> new IdNotExistException("현재 로그인 상태가 아닙니다.", ErrorCode.ID_NOT_EXIST));
        Order order = new Order();
        order.setUser(user);
        order.setOrderStatus(OrderStatus.PENDING);
        order.setPayment(requestOrderFromCartDto.getPayment());
        if(requestOrderFromCartDto.getPayment() == Payment.BANK_ACCOUNT){
            order.setBank(requestOrderFromCartDto.getBank());
            order.setAccount(requestOrderFromCartDto.getAccount());
        }

        orderRepository.save(order);
        List<Cart> cartList = new ArrayList<>();
        for(Long lectureId : requestLectureIdList){
            Cart cart = cartRepository.findByLecture_LectureIdAndUser_UserId(lectureId, user.getUserId())
                    .orElseThrow(() -> new BadRequestArgumentException("장바구니에 없는 강의입니다.", ErrorCode.BAD_REQUEST_ARGUMENT));
            cartList.add(cart);
        }

        List<OrderLecture> orderLectureList = order.getOrderLectures();
        //주문 요청 입력하면 선택한것만 주문한다.
        for(Cart cart : cartList){
            OrderLecture orderLecture = new OrderLecture();
            orderLecture.setLecture(cart.getLecture());
            orderLecture.setOrder(order);
            orderLectureList.add(orderLectureRepository.save(orderLecture));
            cartRepository.deleteByLecture_LectureIdAndUser_UserId(cart.getLecture().getLectureId(), user.getUserId());
        }
        order.setOriginalPrice(orderRepository.findSumOrderByOrderId(order.getOrderId()));
        
        Integer price = order.getOriginalPrice();
        if(requestOrderFromCartDto.getIssuedCouponId() != null) {
            IssuedCoupon issuedCoupon = issuedCouponRepository.findByIssuedCouponId(requestOrderFromCartDto.getIssuedCouponId());
            if (issuedCoupon == null) {  //없는 쿠폰 입력했을 때
                throw new IdNotExistException("존재하지 않는 쿠폰입니다", ErrorCode.ID_NOT_EXIST);
            }
            // 이미 사용한 쿠폰 입력했을 때 or 유효하지 않는 쿠폰 입력했을 때
            if (issuedCoupon.isCouponUsed() || LocalDateTime.now().isAfter(issuedCoupon.getCouponValidDate())) {
                throw new BadRequestArgumentException("이미 사용했거나 유효하지 않은 쿠폰입니다", ErrorCode.BAD_REQUEST_ARGUMENT);
            }
            order.setIssuedCoupon(issuedCoupon);
            issuedCoupon.setCouponUsed(true);

            if(fixDiscountCouponRepository.existsByCouponId(issuedCoupon.getCoupon().getCouponId())){
                Optional<FixDiscountCoupon> fixDiscountCoupon = fixDiscountCouponRepository.findByCouponId(issuedCoupon.getCoupon().getCouponId());
                if(fixDiscountCoupon.get().getDiscountPrice() > order.getOriginalPrice()) throw new BadRequestArgumentException("쿠폰을 적용할 수 없습니다.", ErrorCode.BAD_REQUEST_ARGUMENT);
                price -= fixDiscountCoupon.get().getDiscountPrice();
            }
            else if(rateDiscountCouponRepository.existsByCouponId(issuedCoupon.getCoupon().getCouponId())){
                Optional<RateDiscountCoupon> rateDiscountCoupon = rateDiscountCouponRepository.findByCouponId(issuedCoupon.getCoupon().getCouponId());
                double ratePrice = ((100-rateDiscountCoupon.get().getDiscountRate())*0.01);
                price = (int)(price * ratePrice);
            }
        }

        order.setSalePrice(price);
        orderRepository.save(order);

    }
```

2022-03-01 11:54 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/purchase/PurchaseServiceImpl.java
> +                    Student student = new Student();
이런 부분도 에러 던지고 if else로 분기한 부분을 지워주셔요!

2022-03-01 12:14 UTC, zmfl1230 requested changes

2022-03-01 12:14 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/purchase/PurchaseServiceImpl.java
>              if(order.getSalePrice() == null){ // 할인가격이 없으면 원가만
요고는 기본적으로 order.getSalePrice 건 order.getOriginalPrice 할인가가 없으면, 같은 값이 저장되는게 맞지 않을까요~?
그러면 저 if-else로 분기한건 그냥 `purchase.setPurchasePrice(order.getSalePrice());` 로 통일할 수 있겠지요~
위에 [createOrder 참고용 코드](https://github.com/intensive-study/remote-class-project-server/pull/46/files#r816701039)에는 제가 반영되게 해놨습니다!

2022-03-01 12:14 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/purchase/PurchaseServiceImpl.java
> +                    Lecture lecture = lectureRepository.findById(orderLecture.getLecture().getLectureId())
```
if(studentRepository.existsByLecture_LectureIdAndUser_UserId(orderLecture.getLecture().getLectureId(), user.getUserId())) {
throw new BadRequestArgumentException("이미 수강하고 있는 강의입니다.", ErrorCode.BAD_REQUEST_ARGUMENT);
}
```

이미 요 코드를 통해 존재하는 강좌임을 확인햇는데 또 검증할 필요가 있을까요~? (물론 아무런 값이나 넣은 상황을 배제한 의견이고, 문제의 상황은 운영상에선 발생할 것 같지 않아보여요!)
Lecture가 필요하다면 아래처럼 사용가능합니다! (한번 더 쿼리를 날릴 필요가 없어보여요!)
```
student.setLecture(orderLecture.getLecture());
```

2022-03-01 12:14 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/purchase/PurchaseServiceImpl.java
>          else{
그리고 사실 create purchase 서비스는 order status를 complete로 바꾸라는 요청이 오면 이 서비스함수가 실행될 필요가 있어보여요! (예를 들면 클라이언트에서 /order/complete와 같은 요청이 있을때, status가 complete로 바뀌는 시점에 이 서비스 로직이 실행되게요! 지금처럼 Rest API endpoint가 아닌) 
그러면 아래처럼 주문 상태에 따라 이런 에러를 날릴 필요도 없겠쬬!
```throw new BadRequestArgumentException("주문 가능한 상태가 아닙니다", ErrorCode.BAD_REQUEST_ARGUMENT);```

2022-03-01 13:29 UTC, yijinKim commented on src/main/java/org/server/remoteclass/controller/PurchaseController.java
> +    public ResponseEntity cancelPurchase(@RequestParam("purchaseId") Long purchaseId, @RequestParam(value = "lectureId", required = false, defaultValue = "") List<Long> lectureIdList) {
url이 길어지는 경우는 생각 못했네요 수정하겠습니다

2022-03-01 13:39 UTC, zmfl1230 requested changes

2022-03-01 13:39 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/purchase/PurchaseServiceImpl.java
> +        if(prevPurchase.get().isValidPurchase() == false){
요런거는 왠만하면 !!
```
if(!prevPurchase.get().isValidPurchase())
```

2022-03-01 13:39 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/purchase/PurchaseServiceImpl.java
> +        Optional<Purchase> prevPurchase = purchaseRepository.findById(purchaseId);
요건 값이 존재하는지 여부 체크 안해주나요~?!

2022-03-01 13:39 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/purchase/PurchaseServiceImpl.java
> +        Optional<Purchase> prevPurchase = purchaseRepository.findById(purchaseId);
prevPurchase, prevOrder 둘다 마찬가지입니다.!

2022-03-01 13:47 UTC, yijinKim commented on src/main/java/org/server/remoteclass/service/order/OrderServiceImpl.java
> +        order.setOrderStatus(OrderStatus.PENDING);
현재 orderStatus가 default값으로 설정이 안되는 문제가 있어서 일단 해당 부분은 살려두겠습니다. 문제가 해결되는대로 그부분 삭제할게요!

2022-03-01 14:19 UTC, yijinKim commented on src/main/java/org/server/remoteclass/service/order/OrderServiceImpl.java
> +    public void createOrderFromCart(RequestOrderFromCartDto requestOrderFromCartDto, List<Long> requestLectureIdList) {
네 감사합니다!! 참고해서 수정하겠습니다!!

2022-03-01 14:38 UTC, yijinKim commented on src/main/java/org/server/remoteclass/service/purchase/PurchaseServiceImpl.java
> +        Optional<Purchase> prevPurchase = purchaseRepository.findById(purchaseId);
orElseThrow로 값 체크하고 IdNotException로 에러처리했습니다.

2022-03-01 14:40 UTC, yijinKim commented
지금 수정하지 못한 if-else문과 같은 정리는 해당 풀리퀘를 머지하고 refactor 브랜치를 새로 파서 더 정리할 예정입니다.

2022-03-01 15:59 UTC, merged