feat: add lecture crud(in progress)
intensive-study/remote-class-project pull request #9
Opened 2022-01-30 15:39 UTC by yijinKim

아직 진행중인 코드입니다만 lecture부분 코드리뷰 부탁드립니다

2022-01-30 15:52 UTC, gusdn3477 approved these changes

2022-01-30 15:52 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/controller/LectureController.java
> +    }
우선 create, read, update 등과 같은 행위는 method로 의미를 전달할 수 있기에 명시해 주지 않습니다.
[이 링크 한번 읽어 보세요](https://sanghaklee.tistory.com/57)
Post의 경우 그냥 /lecture 로 하셔도 될 것 같아요.

2022-01-30 15:52 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/service/LectureServiceImpl.java
> +    }
다른 조회 함수에도 @Transactional 맞춰주시면 좋을 것 같아요!

2022-01-30 15:52 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/service/LectureServiceImpl.java
> +//        lecture.setEndDate(lectureDto.getEndDate());
혹시 save 함수 적용하지 않아도 업데이트 되나요?
제가 JPA쪽 개념이 확실하지 않아 질문 드립니다.
그리고 findBy문의 경우 예외처리 해 주시면 나중에 리팩토링 시에 훨씬 편해질 것 같아요!

2022-01-31 12:27 UTC, yijinKim commented on src/main/java/org/server/remoteclass/controller/LectureController.java
> +    }
네 참고해서 수정하겠습니다!

2022-01-31 13:39 UTC, zmfl1230 requested changes

2022-01-31 13:39 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/LectureServiceImpl.java
> +//        lecture.setEndDate(lectureDto.getEndDate());
save 함수 적용하지 않아도 jpa 자체 변경감지 기능으로 자동 업데이트 쿼리 날라갑니다@!

2022-01-31 13:39 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/vo/ResponseLecture.java
> +public class ResponseLecture {
흠,,, 이 response, request Lecture를 VO안에 넣으신 이유가 무엇일까요~?
VO는 일반적으로 불변객체를 만들기 위한 value object입니다~ 값 타입으로 쓰이곤 하죠!
아직, 사용하신 클래스들이 아니라 어디에 쓰실지 잘 모르겠으나 작성하신 코드상 DTO가 더 적합해 보이네요!

2022-01-31 13:39 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/entity/LectureEntity.java
> +public class LectureEntity {
entity/ 하위에 만든 클래스이니 entity의 소속이라는 것이 명확한 상황입니다. 이때는 클래스명을 `Lecture` 라고 해주시는게 좋을 것 같아요~! (다른 entity 클래스명도 마찬가지입니다!  하지만, 필요에 따라서 엔티티 명이 겹칠 수도 있는 상황은 배제해야겠지요! -> 사실 엔티티 명이 겹칠 수 있는 상황은 별로 없다고 생각합니다. 각 엔티티 별 명확한 역할이 있기 때문에!)
비록 지금 @Table 어노테이션을 쓰셔서 lecture라는 테이블로 이 엔티티가 매핑이 되겠지만, 그냥 Lecture 로 엔티티 명을 만들어주시면 Lecture라는 이름으로 테이블이 생성되기 떄문에 저 어노테이션도 필요없을 것 같아요~!

2022-01-31 13:53 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/service/LectureServiceImpl.java
> +//        lecture.setEndDate(lectureDto.getEndDate());
감사합니다!

2022-01-31 14:49 UTC, yijinKim commented on src/main/java/org/server/remoteclass/vo/ResponseLecture.java
> +public class ResponseLecture {
이부분은 제가 리팩토링 과정에서 뺄 예정이었습니다. 바로 정리해놓겠습니다!request Lecture은 LectureFormDto로 수정할 계획입니다!!

2022-01-31 14:50 UTC, yijinKim commented on src/main/java/org/server/remoteclass/entity/LectureEntity.java
> +public class LectureEntity {
네 이부분 수정하겠습니다!

2022-01-31 15:32 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/entity/LectureEntity.java
> +public class LectureEntity {
> 클래스명은 수정하겠습니다. @table 어노테이션을 쓰지않아도 jpa 엔티티가 매핑되나요?

@ entity가 jpa 엔티티 매핑의 역할을 하는 것으로 알고 있습니다.
@ table은 db에 생성할 테이블 이름 설정의 기능 및 제약 조건과 같은 것들을 테이블 단위로 설정할 수 있는 어노테이션으로 알고 있습니다.
@ 과 단어를 붙여 사용시에 태그가 되버려서 한 칸 띄어쓰기 양해 바랍니다!

2022-01-31 15:33 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/vo/ResponseLecture.java
> +public class ResponseLecture {
> 이부분은 제가 리팩토링 과정에서 뺄 예정이었습니다. 바로 정리해놓겠습니다!request Lecture은 LectureFormDto로 수정할 계획입니다!!
제가 예전 퀴즈 프로젝트 시에 vo를 잘못 사용했던 것 같네요.

2022-01-31 15:45 UTC, yijinKim commented on src/main/java/org/server/remoteclass/entity/LectureEntity.java
> +public class LectureEntity {
> @ entity가 jpa 엔티티 매핑의 역할을 하는 것으로 알고 있습니다. @ table은 db에 생성할 테이블 이름 설정의 기능 및 제약 조건과 같은 것들을 테이블 단위로 설정할 수 있는 어노테이션으로 알고 있습니다. @ 과 단어를 붙여 사용시에 태그가 되버려서 한 칸 띄어쓰기 양해 바랍니다!

네 설명감사합니다!!

2022-02-03 05:36 UTC, gusdn3477 requested changes

2022-02-03 05:36 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/controller/LectureController.java
> +    }
29번째 라인과 같은 상황에서 정확한 표현 방법을 잘 모르겠네요. 이것도 저희끼리 통일을 시켜야 할까요?
@ PostMapping만 쳐도 되는 것 같고, 저는 @ PostMapping("/")으로 해줬던 것으로 기억하는데, 뭐가 좋은 방법일지 고민해보겠습니다.

또 dto에 관해 공부해 본 결과, Entity -> Service 단에서는 자료형이 Entity고, Service -> Controller는 Dto라고 하네요.

2022-02-03 05:36 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/entity/Category.java
> +@ Setter
Data 어노테이션에 Setter, Getter가 포함되어 있습니다!

2022-02-03 06:29 UTC, yijinKim commented on src/main/java/org/server/remoteclass/entity/Category.java
> +@ Setter
네 이부분 검색해보니 Data어노테이션은 무분별하게 쓰면 좋지 않다고 나와서 Getter, Setter로 수정하려고 합니다.([참고링크](https://velog.io/@rosa/Lombok-%EC%A7%80%EC%96%91%ED%95%B4%EC%95%BC-%ED%95%A0-annotation))

2022-02-03 06:45 UTC, yijinKim commented on src/main/java/org/server/remoteclass/controller/LectureController.java
> +    }
1) 매핑방법이 다양하게 나오는걸 보니 같이 상의해서 리팩토링 해야할것같아요.
2) 네 이부분도 리팩토링하겠습니다. 저는 이 [내용](https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/)을 봤는데 현우님 말씀대로 현재의 코드에서는  controller에 나와있는 entity를 모두 service단에서 변환해야할 것 같습니다. 추후에 리팩토링해서 다시 올려보겠습니다...

2022-02-03 07:24 UTC, yijinKim commented
현재 Lecture에서 제가 임의로 추가한 내용은 강의자가 강좌를 새로 만들때 author(작성자) 부분을 새로 추가했습니다. 참고부탁드립니다.

2022-02-03 11:23 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/entity/Category.java
> +@ Setter
저도 바꿔야겠네요. 감사합니다.

2022-02-03 15:32 UTC, zmfl1230 requested changes

2022-02-03 15:32 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/controller/LectureController.java
> +    }
음,,, 매핑방법으로는 제 생각에는 그냥 `@RequestMapping("/lecture")` 로 지정해 주셨으면, 
`@PostMapping`  만 적어주셔도 되고, @PostMapping"()" 이 부분은 안붙여 주셔도 될 것 같아요!

2022-02-03 15:32 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/LectureServiceImpl.java
> +    public List<Lecture> getLectureByCategoryId(Long categoryId) throws IdNotExistException{
음,, 카테고리 아이디가 0 이하의 값이 들어오는 경우도 있을까요!!?~?
카테고리가 9개 생성돼서 아이디가 9까지 배분이 됐는데 10으로 요청한 경우는 어떻게 될까요?!!

2022-02-03 15:32 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/LectureServiceImpl.java
> +    public List<Lecture> getLectureByCategoryId(Long categoryId) throws IdNotExistException{
흠,,, 어떤 카테고리 ID로 강의를 조회하는데 카테고리는 등록이 돼 있는데 그 카테고리를 사용하고 있는 강의는 없을 수도 있지 않을까요~? 그럼 그냥 빈값을 반환하는게 맞지 않을까요~? 어떤 카테고리로 등록된 강의를 조회하고자 하는데 그 카테고리로 등록된 강의가 없으면 없는대로 반환하는게 맞는 것 같아서 말씀드려봅니다!!!

`존재하지 않는 강의` 는 어떤 잘못된 강의 아이디로 강의 페이지에 접근하고자 할 때, 예를 들면 강의는 9번까지 생성돼 있는 상황에서 10번 강의를 조회하고자 할 때 존재하지 않는 강의란 표현이 적절한 것 같아요!

2022-02-03 15:32 UTC, zmfl1230 commented on src/main/java/org/server/remoteclass/service/LectureServiceImpl.java
> +    public Lecture createLecture(LectureFormDto lectureFormDto) throws IdNotExistException {
서비스 계층은 @Transactional 붙여주시는게 맞습니다~! 비즈니스 로직 단위로 트랜젝션이 처리되기 때문에 그래야 JPA 좋은 기능들을 써먹을 수 있습니다. (쓰기 지연과 같은) 
+ 추가적으로 @Transactional 안 붙여주셨을 때, createLecture 호출 시 에러 안나셨나요~?

2022-02-03 15:42 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/controller/LectureController.java
> +    }
`@PostMapping`이 나아보이네요!

2022-02-03 16:15 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/service/LectureServiceImpl.java
> +                .orElseThrow(() -> new IdNotExistException("존재하지 않는 사용자", ResultCode.ID_NOT_EXIST));
아마 findOneWithAuthoritiesByEmail을 사용하는 부분이 모두 바뀔 겁니다.. userAuthority 테이블이 없어졌거든요. 여하튼 merge를 잘 해봐야 겠습니다..

2022-02-03 16:15 UTC, gusdn3477 commented on src/main/java/org/server/remoteclass/service/LectureServiceImpl.java
> +    public List<Lecture> getLectureByCategoryId(Long categoryId) throws IdNotExistException{
프론트엔드를 구현하게 된다면, 번호 대신 카테고리 이름이 나오겠죠?
만약 -1이나 지영님이 말씀하신 것처럼 10으로 요청하게 된다면(사실 이건 억지로 요청하는 거긴 해요)
1) 예외처리를 케이스에 맞게 나눠서 하거나
2) 그냥 findById의 결과를 반환해 주는 것이 좋다고 생각해요!

저는 개인적으로 2번에 한 표입니다. 
-1을 고려하게 되면 0.5, 혹은 INT 범위를 초과하는 요청도 가능하거든요. 이런 모든 예외에 처리를 할 수 있나? 싶긴 합니다.

2022-02-03 16:15 UTC, gusdn3477 commented on src/main/resources/data.sql
> +INSERT INTO authority (AUTHORITY_NAME) values ('ROLE_ADMIN');
이 부분이 사라질 예정입니다.

2022-02-04 01:22 UTC, yijinKim commented on src/main/java/org/server/remoteclass/service/LectureServiceImpl.java
> +    public List<Lecture> getLectureByCategoryId(Long categoryId) throws IdNotExistException{
해결했습니다!

2022-02-04 01:39 UTC, merged